"""added unique constraints

Revision ID: e946d29c8de5
Revises: a434f5a344d3
Create Date: 2019-12-18 09:38:29.507911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e946d29c8de5'
down_revision = 'a434f5a344d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_category_name_uc', 'categories', ['name'])
    op.create_unique_constraint('_employee_interest_uc', 'employee_interests', ['employee_id', 'interest_id'])
    op.create_unique_constraint('_gift_category_uc', 'gift_categories', ['gift_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_gift_category_uc', 'gift_categories', type_='unique')
    op.drop_constraint('_employee_interest_uc', 'employee_interests', type_='unique')
    op.drop_constraint('_category_name_uc', 'categories', type_='unique')
    # ### end Alembic commands ###
